name: Clang-tidy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install clang-tidy
      run:  sudo apt-get install -y clang-tidy

    - name: Generate compile_commands.json
      run:  cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ${{github.workspace}}

    # Run tidy check but alarm only for SEI CERT Secure Coding Standard errors
    - name: Run clang-tidy
      run:  clang-tidy -checks=* -warnings-as-errors=cert-* ${{github.workspace}}/src/**/*.cpp
